server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/security_test_db
    username: postgres
    password: 123
jwt:
#  secret: TransportManagementSystemSecRetKeyValueForJwtToken
  validation-time: 36000
#  refresh-time: 86400000

#openapi:
#  local-url: http://localhost:8088
